[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
version = "0.0.0"
name = "python-api-template"
authors = [
    {name = "Morten Fredriksen", email = "morfre@equinor.com"}
]
readme = "README.md"
dependencies = [
    "fastapi[all]",
    "msal"
]
